# This example workflow will build container image
# of the application using source to image build
# startegy and push the image to quay.io (Image registry)

name: S2I build and push
on: [push, workflow_dispatch, pull_request]
env:
  IMAGE_REGISTRY: quay.io
  REGISTRY_USER: tetchell
  APP_NAME: petclinic
  IMAGE_TAGS: latest

jobs:
  test-s2i-job:
    runs-on: ubuntu-20.04
    name: S2I build and push
    steps:
      # Checkout spring petclinic repository
      - name: Checkout
        uses: actions/checkout@v2

      # Setup S2i and Build container image
      - name: Setup and Build
        uses: redhat-actions/s2i-build@v1
        with:
          path_context: '.'
          tag: ${{ env.IMAGE_TAG }}
          builder_image: 'registry.access.redhat.com/openjdk/openjdk-11-rhel7'
          image_name: ${{ env.APP_NAME }}

      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.APP_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_USER }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
